DELETE FROM `AppGearPlatformModelPropertyRelationship` WHERE id < 1000;
DELETE FROM `AppGearPlatformRelationship` WHERE id < 1000;
DELETE FROM `AppGearPlatformModelPropertyFieldScalarStringText` WHERE id < 1000;
DELETE FROM `AppGearPlatformModelPropertyFieldScalarString` WHERE id < 1000;
DELETE FROM `AppGearPlatformModelPropertyFieldScalarInteger` WHERE id < 1000;
DELETE FROM `AppGearPlatformModelPropertyFieldScalarId` WHERE id < 1000;
DELETE FROM `AppGearPlatformModelPropertyFieldScalarFloat` WHERE id < 1000;
DELETE FROM `AppGearPlatformModelPropertyFieldScalarDatetime` WHERE id < 1000;
DELETE FROM `AppGearPlatformModelPropertyFieldScalarBoolean` WHERE id < 1000;
DELETE FROM `AppGearPlatformModelPropertyFieldScalar` WHERE id < 1000;
DELETE FROM `AppGearPlatformModelPropertyField` WHERE id < 1000;
DELETE FROM `AppGearPlatformModelProperty` WHERE id < 1000;
UPDATE SystemModel SET parent_id = NULL WHERE parent_id < 1000;
DELETE FROM `AppGearPlatformModel` WHERE id < 1000;
UPDATE SystemModelScope SET parent_id = NULL WHERE parent_id < 1000;
DELETE FROM `AppGearPlatformModelScope` WHERE id < 1000;

SET FOREIGN_KEY_CHECKS=0;
INSERT IGNORE INTO `AppGearPlatformModelPropertyRelationship` SELECT * FROM p.`AppGearPlatformModelPropertyRelationship` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformRelationship` SELECT * FROM commerce.`AppGearPlatformRelationship` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformModelPropertyFieldScalarStringText` SELECT * FROM commerce.`AppGearPlatformModelPropertyFieldScalarStringText` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformModelPropertyFieldScalarString` SELECT * FROM commerce.`AppGearPlatformModelPropertyFieldScalarString` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformModelPropertyFieldScalarInteger` SELECT * FROM commerce.`AppGearPlatformModelPropertyFieldScalarInteger` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformModelPropertyFieldScalarId` SELECT * FROM commerce.`AppGearPlatformModelPropertyFieldScalarId` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformModelPropertyFieldScalarFloat` SELECT * FROM commerce.`AppGearPlatformModelPropertyFieldScalarFloat` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformModelPropertyFieldScalarDatetime` SELECT * FROM commerce.`AppGearPlatformModelPropertyFieldScalarDatetime` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformModelPropertyFieldScalarBoolean` SELECT * FROM commerce.`AppGearPlatformModelPropertyFieldScalarBoolean` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformModelPropertyFieldScalar` SELECT * FROM commerce.`AppGearPlatformModelPropertyFieldScalar` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformModelPropertyField` SELECT * FROM commerce.`AppGearPlatformModelPropertyField` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformModelProperty` SELECT * FROM commerce.`AppGearPlatformModelProperty` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformModel` SELECT * FROM commerce.`AppGearPlatformModel` WHERE id < 1000 ORDER BY id ASC;
INSERT IGNORE INTO `AppGearPlatformModelScope` SELECT * FROM commerce.`AppGearPlatformModelScope` WHERE id < 1000 ORDER BY id ASC;
SET FOREIGN_KEY_CHECKS=1;